### ISSUE TITLE
API implementation for self-hosted DB

### ISSUE THREAD

**Issue by adampax** [gionoa/Formula1API#38]
Hi @gionoa, thanks for sharing this! I appreciate you setting this up, especially the models for Ergast responses.  

I'm working against a self-hosted copy of the Ergast DB, and in your Readme under [deploying and publishing,](https://github.com/gionoa/Formula1API#deploying--publishing) you recommended this [nodejs repo](https://github.com/Edivad99/NJS-ErgastF1API).  That repo works well for querying against my own db, but I wanted to point out that the url endpoints don't match up with those of the original Ergast API. 

For example, getting drivers standings on Ergast:

`https://ergast.com/api/f1/2008/driverStandings.json`

Would have to be something like this in the node api:

`http://localhost:5001/standings/drivers?year=2008`

That being the case, I'd don't think think it would work as a drop in replacement to use your library against.

Are you using something else for your custom api? Or maybe I'm wrong and this library supports that url format?

Thanks again for sharing this.

**Comment by gionoa** [comment]
Apologies for the late reply, @adampax! Huge thanks for checking out my repo. To be honest, I have no working knowledge of the nodes repo nor working with my custom API. I just focused on facilitating fetching F1 data within a Swift context so that the developer wouldn't have to that themselves. 

If you're looking to use this within a server context, and would like for me to modify it somehow (I'd definitely like to learn or open it up for you to make a PR, however you like) I'd be happy to.

**Comment by adampax** [comment]
No worries @gionoa. I wound up doing a partial definition of some of the Ergast endpoints in [OpenAPI](https://github.com/OAI/OpenAPI-Specification/), then I'm going to use that to generate the node library that hopefully matches what Ergast is returning. 

Digging a little deeper on that other node repo, I think some folks were looking into rebuilding the Ergast API in node, but didn't go through with it.

**Comment by gionoa** [comment]
Sweet! Closing for now, feel free to come back if you want to take another look 😄
